controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\CoreUser;
use app\models\Order;
use app\models\Product;
use Yii;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\HttpException;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout', 'show-cart', 'view-order', 'verify-hash', 'render-cart', 'remove-item'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $this->manageSession();
        $hash = Yii::$app->session->get('hash');
        $products = Product::findAllNoCondition();
        return $this->render('index', ['products' => $products, 'hash' => $hash]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionAddProduct()
    {
        if (Yii::$app->request->isAjax) {
            $this->manageSession();
            $hash = Yii::$app->session->get('hash');
            $productId = intval(Yii::$app->request->post('productId'));
            $product = Product::findOne($productId);
            if (!$product) {
                throw new HttpException(400, 'No such product!');
            }
            $quantity = intval(Yii::$app->request->post('quantity'));
            $orderModel = Order::findOne(['hash' => $hash, 'status' => 0]);
            if (!$orderModel) {
//                $sql = "SELECT AUTO_INCREMENT FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'users'";
//                $nextUserId = Yii::$app->db->createCommand($sql)->execute();
                $user = CoreUser::createNewUser();
            } else {
                $currentDay = date('Y-m-d');
                if ($orderModel->valid_until < $currentDay) {
                    $this->clearInvalidData($orderModel);
                    $user = CoreUser::createNewUser();
                } else
                    $user = CoreUser::findOne($orderModel->user_id);
            }

            $order = Order::findOne([
                'hash' => $hash,
                'user_id' => $user->id,
                'product_id' => $productId,
                'status' => 0
            ]);
            if (empty($order)) {
                $order = new Order();
                $order->hash = $hash;
                $order->product_id = $productId;
                $order->user_id = $user->id;
                $order->status = 0;
            }

            $order->quantity += $quantity;
            $order->price = $product->price;
            $endDate = new \DateTime();
            $endDate->modify('+5 day');
            $order->valid_until = $endDate->format('Y-m-d');
            $order->save();

            // update all rows of the order with the new date end validity
            Yii::$app->db->createCommand()
                ->update(Order::tableName(), [
                    'valid_until' => $endDate->format('Y-m-d')
                ], 'hash=:hash', [':hash' => $order->hash])->execute();
            $q = new Query();
            $totalNumberOfProducts = $q->select('SUM(quantity)')
                ->from(Order::tableName())
                ->where('hash=:hash', [':hash' => $hash])->createCommand()->queryScalar();
            return json_encode([$quantity, $totalNumberOfProducts, $hash]);
        }
    }

    public function actionShowCart($hash = null)
    {
        $this->manageSession();
        $hash = Yii::$app->session->get('hash');
        $order = Order::findOne(['hash' => $hash]);
        $currentDay = date('Y-m-d');
        if ($order && $order->valid_until < $currentDay) {
            $this->clearInvalidData($order);
            $user = CoreUser::createNewUser();
        }
        if (!empty($_POST['ids']) && !empty($_POST['quantities']) && !empty($_POST['email'])) {
            $productIds = $_POST['ids'];
            $quantities = $_POST['quantities'];
            $username = strip_tags($_POST['name']);
            $email = strip_tags(filter_var($_POST['email'], FILTER_SANITIZE_EMAIL));
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $order = Order::findOne(['hash' => $hash]);
                $user = CoreUser::findOne($order->user_id);
                $user->name = $username;
                $user->email = $email;
                $user->save();
                foreach ($productIds as $key => $productId) {
                    Yii::$app->db->createCommand()
                        ->update(Order::tableName(), [
                            'quantity' => $quantities[$key],
                            'status' => 1
                        ], 'hash=:hash AND product_id=:id',
                            [
                                ':hash' => $hash,
                                ':id' => $productId,
                            ])->execute();
                }

                $transaction->commit();
                $orders = Order::findAll(['hash' => $hash, 'status' => 1]);
                $totalSum = 0;
                foreach ($orders as $order) {
                    $totalSum += $order->quantity * $order->price;
                }
                Yii::$app->session->setFlash('success', 'Your order has been received! Thank you!');
                Yii::$app->session->set('orderSuccess', 1);
                $message = $this->renderPartial('_emailMessage', ['user' => $user, 'hash' => $hash, 'orders' => $orders, 'totalSum' => $totalSum]);
                $headers = "Content-type: text/html; charset=UTF-8\r\n";
                mail($email, 'Your order from our Gun site', $message, $headers);
            } catch (\Exception $e) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', 'Something went wrong!');
                Yii::$app->session->set('orderSuccess', 0);
            }
        }
        $orders = Order::findAll(['hash' => $hash, 'status' => 0]);

        // update the prices for the current order
        foreach ($orders as $order) {
            $order->price = $order->getProduct()->one()->price;
            $order->save();
        }
        return $this->render('showCart', ['orders' => $orders]);
    }

    public function actionViewOrder()
    {
        $this->manageSession();
        $hash = $_GET['hash'];
        $order = Order::findOne(['hash' => $hash]);
        if (empty($order)) {
            return $this->render('error');
        }

        $orders = Order::findAll(['hash' => $hash]);
        return $this->render('viewOrder', ['orders' => $orders]);
    }

    public function actionVerifyHash()
    {
        $this->manageSession();
        /* @var $order Order */
        $hash = $_POST['hash'];
        $order = Order::findOne(['hash' => $hash, 'status' => 0]);
        if ($order) {
            if ($order->valid_until < date('Y-m-d')) {
                // the order is expired
                $this->clearInvalidData($order);
                $hash = $this->generateHash();
            }
        } else {
            // no active order at all
            $hash = $this->generateHash();
        }
        Yii::$app->session->set('hash', $hash);
        return $hash;
    }

    public function actionRenderCart()
    {
        $this->manageSession();
        $hash = $_POST['hash'];
        $orders = Order::findAll(['hash' => $hash, 'status' => 0]);
        $totalSum = 0;
        foreach ($orders as $order) {
            $totalSum += $order->quantity * $order->price;
        }
        return $this->renderPartial('_renderCart', ['orders' => $orders, 'totalSum' => $totalSum]);
    }

    public function actionRemoveItem()
    {
        if (Yii::$app->request->isAjax) {
            $productId = $_POST['productId'];
            $hash = $_POST['hash'];
            Yii::$app->db->createCommand()
                ->delete(Order::tableName(), 'hash=:hash AND product_id=:id', [
                    ':hash' => $hash,
                    ':id' => $productId
                ])->execute();
        }
    }

    private function generateHash()
    {
        $date = microtime();
        $salt = mt_rand(0, 500000000);
        $hash = md5($date) . md5($salt);

views/site/_emailMessage.php
<?php
/**
 * Created by PhpStorm.
 * User: Asen
 * Date: 8.7.2016 г.
 * Time: 23:19
 */
/* @var $user \app\models\CoreUser */
?>
Hello <?= $user->name ?> . ', you have successfully confirmed your order! You can view the order from
<a href="<?= Yii::$app->urlManager->createAbsoluteUrl(['site/view-order', 'hash' => $hash]) ?>">HERE</a><br/>
Also here is your order again <br/>
<table style="border: 1px solid black;border-collapse: collapse">
    <tr>
        <th style="border: 1px solid black;padding: 5px 8px">Product</th>
        <th style="border: 1px solid black;padding: 5px 8px">Quantity</th>
        <th style="border: 1px solid black;padding: 5px 8px">Price</th>
    </tr>
    <?php
    foreach ($orders as $order) { ?>
        <tr>
            <td style="border: 1px solid black;padding: 5px 8px"><?= $order->getProduct()->one()->name ?></td>
            <td style="border: 1px solid black;padding: 5px 8px"><?= $order->quantity ?></td>
            <td style="border: 1px solid black;padding: 5px 8px"><?= $order->price ?></td>
        </tr>
    <?php } ?>
</table>
<h2>TOTAL SUM: <?= number_format($totalSum, 2) ?></h2>

<br/>Thank you!

views/site/_renderCart.php
<?php
/**
 * Created by PhpStorm.
 * User: Asen
 * Date: 8.7.2016 г.
 * Time: 21:08
 */
use yii\bootstrap\ActiveForm;

if (!empty($orders)) {
    $form = ActiveForm::begin([
        'action' => Yii::$app->urlManager->createAbsoluteUrl('site/show-cart')
    ]); ?>
    <table class="table table-bordered">
        <tr>
            <th>Name of the item</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total Price</th>
            <th></th>
        </tr>
        <?php
        /* @var $order \app\models\Order */
        foreach ($orders as $order) {
            $product = $order->getProduct()->one(); ?>
            <input type="hidden" name="ids[]" value="<?= $product->id ?>"/>
            <tr>
                <td><?= $product->name ?></td>
                <td>
                    <input class="quantity" type="number" min="1" value="<?= $order->quantity ?>" name="quantities[]"/>
                </td>
                <td class="price"><?= $product->price ?></td>
                <td class="totalPrice"><?= number_format($product->price * $order->quantity, 2) ?></td>
                <td>
                    <a href="#" data-id="<?=$product->id?>" class="deleteRow" title="Remove item!"><i class="fa fa-close fa-2x red"></i></a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div id="globalSum" class="pull-right" style="clear: both"><h1>Total: <?= number_format($totalSum, 2) ?></h1>
    </div>
    <div>
        <label for="name">Please, enter your name * </label>
        <input type="text" id="name" name="name" required/>
    </div>
    <div>
        <label for="email">Please, enter your email * </label>
        <input type="email" id="email" name="email" required/>
    </div>
    <?= \yii\helpers\Html::submitButton('Order now!', ['class' => 'btn btn-primary']) ?>
    <?php ActiveForm::end();
} else { ?>
    <h3 class="text-center">You haven't ordered yet anything!</h3>
<?php } ?>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1>The requested order is not exists!</h1>

</div>

views/site/index.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Guns & Rouses';
?>
<div class="site-index">


    <div class="body-content">
        <div class="row">
            <?php
            /* @var $product \app\models\Product */
            foreach ($products as $product) { ?>
                <div class="item row-fluid">
                    <div class="col-sm-12"><?= $product->name ?>
                        <span class="priceContent">$ <?= $product->price ?></span>
                    </div>
                    <div class="col-sm-4">
                        <?= Html::textInput('price_' . $product->id, 1, ['min' => 1, 'type' => 'number']) ?>
                    </div>
                    <div class="col-sm-8">
                        <?= Html::button('Добави в кошницата', ['class' => 'btn btn-primary addOrder', 'data-id' => $product->id]) ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<script>
    $(function () {
        $(document).on('click', '.addOrder', function () {
            var productId = $(this).data('id');
            var quantity = $('input[name="price_' + productId + '"]').val();
            var url = '<?=Yii::$app->urlManager->createUrl('site/add-product')?>';
            $.ajax({
                type: 'POST',
                url: url,
                data: {productId: productId, quantity: quantity}
            }).success(function (data) {
                data = JSON.parse(data);
                $('#cartLink').text('Shopping cart: ' + data[1]);
                hash = data[2];
                localStorage.setItem('gun_order', hash);
                console.log(hash);
                alert('You have successfully added ' + data[0] + ' products!');
            }).error(function (request, status, error) {
                alert(request.responseText);
            })
        })
    })
</script>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/showCart.php
<?php
/**
 * Created by PhpStorm.
 * User: Asen
 * Date: 6.7.2016 г.
 * Time: 20:02
 */
use yii\bootstrap\ActiveForm;

?>

<div class="row">
    <div class="col-sm-12">
        <?php \app\components\Components::printFlashMessages(); ?>
        <div id="shoppingTable"></div>
    </div>
</div>
<script>
    function renderCart() {
        var localHash = localStorage.getItem('gun_order');
        var url = '<?=Yii::$app->urlManager->createAbsoluteUrl('site/render-cart')?>';
        $.ajax({
            url: url,
            type: 'POST',
            data: {hash: localHash}
        }).success(function (data) {
            $('#shoppingTable').html(data);
        });
    }

    $(function () {
        setTimeout(function () {
            renderCart();
        }, 500);

        $(document).on('input', '.quantity', function () {
            var newQuantity = $(this).val();
            var price = parseFloat($(this).parent().parent().find('td.price').text());
            var changeSum = (newQuantity * price).toFixed(2);
            $(this).parent().parent().find('td.totalPrice').text(changeSum);
            var sumsPerRow = $('td.totalPrice');
            var totalSum = 0;
            for (var i = 0; i < sumsPerRow.length; i++) {
                totalSum += parseFloat(sumsPerRow[i].innerText);
            }
            $('#globalSum h1').text('Total: ' + totalSum);
        });

        $(document).on('click', 'a.deleteRow', function () {
            var productId = $(this).data('id');
            $.ajax({
                url: '<?=Yii::$app->urlManager->createUrl('site/remove-item')?>',
                type: 'POST',
                data: {
                    productId: productId,
                    hash: localStorage.getItem('gun_order')
                }
            }).done(renderCart);
        });
    })
</script>

views/site/viewOrder.php
<?php
/**
 * Created by PhpStorm.
 * User: Asen
 * Date: 7.7.2016 г.
 * Time: 23:03
 */
?>
<table id="shoppingTable" class="table table-bordered">
    <tr>
        <th>Name of the item</th>
        <th>Quantity</th>
        <th>Price</th>
    </tr>
    <?php
    /* @var $order \app\models\Order */
    foreach ($orders as $order) {
        $product = $order->getProduct()->one(); ?>
        <input type="hidden" name="ids[]" value="<?= $product->id ?>"/>
        <tr>
            <td><?= $product->name ?></td>
            <td>
                <?= $order->quantity ?>
            </td>
            <td><?= $product->price ?></td>
        </tr>
    <?php } ?>
</table>